import jsPDF from "jspdf";

export const generateATSReport = (analysis: any) => {
  const doc = new jsPDF();

  let y = 20;

  // Title
  doc.setFontSize(22);
  doc.setTextColor(37, 99, 235);
  doc.text("ResumeIQ-AI", 20, y);

  y += 10;

  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text("ATS Resume Analysis Report", 20, y);

  y += 15;

  // ATS Scores
  doc.setFontSize(14);
  doc.text("ATS Scores", 20, y);

  y += 10;

  doc.setFontSize(12);

  doc.text(`ATS Score: ${analysis.atsScore}%`, 20, y);
  y += 8;

  doc.text(
    `Keyword Match: ${analysis.keywordMatch}%`,
    20,
    y
  );
  y += 8;

  doc.text(
    `Weighted ATS: ${analysis.weightedATS.weightedATSScore}%`,
    20,
    y
  );
  y += 8;

  doc.text(
    `Education Match: ${analysis.educationMatch.score}%`,
    20,
    y
  );
  y += 8;

  doc.text(
    `Experience Match: ${analysis.experienceMatch.score}%`,
    20,
    y
  );

  y += 15;

  // Matched Keywords
  doc.setFontSize(14);
  doc.text("Matched Keywords", 20, y);

  y += 8;

  doc.setFontSize(12);

  analysis.matchedKeywords.forEach((keyword: string) => {
    doc.text(`• ${keyword}`, 25, y);
    y += 7;
  });

  y += 5;

  // Missing Keywords
  doc.setFontSize(14);
  doc.text("Missing Keywords", 20, y);

  y += 8;

  doc.setFontSize(12);

  analysis.missingKeywords.forEach((keyword: string) => {
    doc.text(`• ${keyword}`, 25, y);
    y += 7;
  });

  y += 10;

  // AI Summary
  doc.setFontSize(14);
  doc.text("AI Summary", 20, y);

  y += 8;

  doc.setFontSize(11);

  const summary = doc.splitTextToSize(
    analysis.aiSuggestions.summary,
    170
  );

  doc.text(summary, 20, y);

  y += summary.length * 7 + 10;

  // Footer
  doc.setDrawColor(200);

  doc.line(20, y, 190, y);

  y += 8;

  doc.setFontSize(10);

  doc.setTextColor(100);

  doc.text(
    "Generated by ResumeIQ-AI",
    20,
    y
  );

  doc.save("ATS_Report.pdf");
};